name: Robot Tests with Allure and Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Google Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq xvfb libxi6 libgconf-2-4
          
          # Cài đặt Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          
          # Lấy phiên bản Chrome hiện tại
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          MAJOR_VERSION=$(echo "$CHROME_VERSION" | cut -d '.' -f 1)
          echo "Detected Chrome version: $CHROME_VERSION"

          # Lấy đúng phiên bản ChromeDriver tương ứng với Chrome major version
          DRIVER_URL=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" | \
            jq -r --arg ver "$MAJOR_VERSION" '
              .versions[] | select(.version | startswith($ver)) | 
              .downloads.chromedriver[] | select(.platform == "linux64") | .url' | head -1)

          echo "Downloading ChromeDriver from $DRIVER_URL"
          wget -O chromedriver.zip "$DRIVER_URL"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          
          # Xác minh phiên bản
          chromedriver --version
          google-chrome --version

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          npm install -g allure-commandline

      - name: Run Robot Framework tests with Allure (headless mode)
        run: |
          # Chạy bằng X virtual framebuffer để hỗ trợ GUI headless
          xvfb-run robot --listener allure_robotframework:output/allure-results --outputdir output testsuites/

      - name: Generate Allure Report
        run: |
          allure generate output/allure-results -o output/allure --clean

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/allure
